### ISSUE TITLE
Neo pixel ring is not working in rasberi pi 2

### ISSUE THREAD

**Issue by Mizver** [626Pilot/RaspberryPi-NeoPixel-WS2812#9] opened 2016-02-01 05:21 UTC
Neo pixel ring cjmcu-2812-16 is not working in rasberi pi 2 i have test lot of library and lot of code plese send me how to connect and how to test the neo pixel ring plese send me all the steps to test

**Comment by 626Pilot** [comment] 2016-02-04 01:43
Duplicate of existing issue - please see this link for more info: https://github.com/626Pilot/RaspberryPi-NeoPixel-WS2812/issues/6

**Closed as completed by 626Pilot** 2016-02-04 01:43 UTC
